apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-deployment
  labels:
    app: sentiment-analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
      - name: sentiment-analysis
        image: gcr.io/weather-297102/sentiment-analysis
        ports:
        - containerPort: 5000
